# Generated by Django 5.2 on 2025-04-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_lesson_link_to_video'),
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_course',
            field=models.ManyToManyField(blank=True, null=True, related_name='payment', to='materials.course', verbose_name='Оплаченный курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_lesson',
            field=models.ManyToManyField(blank=True, null=True, related_name='payment', to='materials.lesson', verbose_name='Оплаченный урок'),
        ),
    ]
