# Generated by Django 5.2 on 2025-04-29 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_course_owner_lesson_owner'),
        ('users', '0003_alter_payment_payment_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionForUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_for_update', to='materials.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_for_update', to=settings.AUTH_USER_MODEL, verbose_name='Подписка')),
            ],
        ),
    ]
