[program:myapp]
command=docker run -d --network=mynetwork --name lms_systems -p 80:8000 --env-file /home/daniil/LMS-systems/.env
autorestart=true
stderr_logfile=/var/log/lms_systems.err.log
stdout_logfile=/var/log/lms_systems.out.log