# Generated by Django 5.2 on 2025-04-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['title_lesson'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lint_to_video',
            new_name='link_to_video',
        ),
    ]
