# Generated by Django 5.2 on 2025-04-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link_to_video',
            field=models.URLField(verbose_name='Ссылка на видео'),
        ),
    ]
