# Generated by Django 5.2 on 2025-05-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена урока'),
        ),
    ]
