name: Practice CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.5.1'

      - name: Install dependencies
        run: |
          poetry install

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
          CELERY_RESULT_BACKEND: ${{ secrets.CELERY_RESULT_BACKEND }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
          EMAIL_USE_SSL: ${{ secrets.EMAIL_USE_SSL }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        run: poetry run python manage.py test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login in DockerHub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/lms_systems:${{ github.sha }} .

      - name: Push Docker image in DockerHub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/lms_systems:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/lms_systems:${{ github.sha }}
          docker stop lms_systems || true
          docker rm lms_systems || true
          docker run -d --name lms_systems -p 80:8000 \
          -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
          -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
          -e STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} \
          -e CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }} \
          -e CELERY_RESULT_BACKEND=${{ secrets.CELERY_RESULT_BACKEND }} \
          -e EMAIL_HOST=${{ secrets.EMAIL_HOST }} \
          -e EMAIL_PORT=${{ secrets.EMAIL_PORT }} \
          -e EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS }} \
          -e EMAIL_USE_SSL=${{ secrets.EMAIL_USE_SSL }} \
          -e EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }} \
          -e EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }} \
          ${{ secrets.DOCKER_HUB_USERNAME }}/lms_systems:${{ github.sha }}
          EOF
